apiVersion: v1
kind: Service
metadata:
  name: frontend-endpoint
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"http":"HTTP"}'
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: localimage/mod_frontend:0.1
        imagePullPolicy: Never
        ports:
        - name: frontend
          containerPort: 80