# This file contains the sample minimal pod definitions for all of the components that one may need to use Open Match as a match maker.
# You can find the same pod definitions within the sub-folders under the /tutorials/ directory
# Run `kubectl apply -f matchmaker.yaml` to deploy these definitions.

apiVersion: v1
kind: Pod
metadata:
  name: director
  namespace: openmatch
spec:
  containers:
  - name: director
    image: localimage/mod_director:0.1
    imagePullPolicy: Never
  hostname: director
---
apiVersion: v1
kind: Pod
metadata:
  name: matchfunction
  namespace: openmatch
  labels:
    app: openmatch
    component: matchfunction
spec:
  containers:
  - name: matchfunction
    image: localimage/mod_matchfunction:0.1
    imagePullPolicy: Never
    ports:
    - name: grpc
      containerPort: 50502
---
kind: Service
apiVersion: v1
metadata:
  name: matchfunction
  namespace: openmatch
  labels:
    app: openmatch
    component: matchfunction
spec:
  selector:
    app: openmatch
    component: matchfunction
  clusterIP: None
  type: ClusterIP
  ports:
  - name: grpc
    protocol: TCP
    port: 50502
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-endpoint
  namespace: openmatch
  annotations:
    service.alpha.kubernetes.io/app-protocols: '{"http":"HTTP"}'
  labels:
    app: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 80
    protocol: TCP
    name: http
    targetPort: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: openmatch
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: localimage/mod_frontend:0.1
        imagePullPolicy: Never
        ports:
        - name: frontend
          containerPort: 80